name: Noodling with GitHub Actions
on:
  push:
    paths:
      - 'README.md'
  workflow_call:
 
jobs:
  sample_rest_user:
    name: Get some user from some DB
    runs-on: ubuntu-latest
    steps:
      - name: Retrieve user via community action
        id: cmaRestGet
        uses: fjogeleit/http-request-action@v1
        with:
          url: ${{ format('https://reqres.in/api/users/{0}', secrets.USER_ID) }}
          method: 'GET'
      - name: Print user information
        run: |
          echo ${{ steps.cmaRestGet.outputs.headers }}
          echo ${{ steps.cmaRestGet.outputs.response }}   
  get_dad_joke:
    name: A dad joke is your reward!
    runs-on: ubuntu-latest
    needs: sample_rest_user
    steps:
      - name: Get Dad Joke via pwsh
        run: |
          $dadJoke = (Invoke-RestMethod -Method 'Get' -Uri 'https://www.reddit.com/r/dadjokes/random.json?limit=1').data.children[0].data
          Write-Host $dadJoke.title
          Write-Host $dadJoke.selftext
        shell: pwsh