name: Noodling with GitHub Actions
on:
  push:
    paths:
      - 'README.md'
  workflow_call:
 
jobs:
  sample_rest_user:
    name: Validate Mule Configuration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      
      - name: Get Error Configuration in JSON
        id: getErrorConfig
        uses: fabasoad/yaml-json-xml-converter-action@main
        with:
          path: './properties/error-config.yaml'
          from: 'yaml'
          to: 'json'
      
      - name: Debug output
        run: echo "${{ steps.getErrorConfig.outputs.data }}"

      - name: Validate Error Configuration
        id: muleValidation
        uses: fjogeleit/http-request-action@v1
        with:
          url: http://mule-app-config.us-e2.cloudhub.io/api/errorConfig/validate
          method: 'POST'
          data: ${{ steps.getErrorConfig.outputs.data }}
      
      - name: Validation response
        run: |
          echo "Hello there"
  get_dad_joke:
    name: A dad joke is your reward!
    runs-on: ubuntu-latest
    needs: sample_rest_user
    steps:
      - name: Get Dad Joke via pwsh
        run: |
          $dadJoke = (Invoke-RestMethod -Method 'Get' -Uri 'https://www.reddit.com/r/dadjokes/random.json?limit=1').data.children[0].data
          Write-Host $dadJoke.title
          Write-Host $dadJoke.selftext
        shell: pwsh