name: Noodling with GitHub Actions
on:
  push:
    paths:
      - 'README.md'
 
jobs:
  get_dad_joke:
    name: Get a Dad Joke
    runs-on: ubuntu-latest
    steps:
      - name: Get random from /r/dadjokes and print
        run: |
          $dadJoke = (Invoke-RestMethod -Method 'Get' -Uri 'https://www.reddit.com/r/dadjokes/random.json?limit=1').data.children[0].data
          Write-Host $dadJoke.title
          Write-Host $dadJoke.selftext
        shell: pwsh
      - name: Git (see what I did there) another
        id: cmaRestGet
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://www.reddit.com/r/dadjokes/random.json?limit=1'
          method: 'GET'
      - name: Print Joke Number 2
        run: |
          echo ${{ fromJson(steps.cmaRestGet.outputs.response).data.children[0].data.title }}
          echo ${{ fromJson(steps.cmaRestGet.outputs.response).data.children[0].data.selftext }}      