name: Noodling with GitHub Actions
on:
  push:
    paths:
      - 'README.md'
  workflow_call:
 
jobs:
  sample_rest_user:
    name: Get some user from some DB
    runs-on: ubuntu-latest
    steps:
      - name: Validate Error Configuration
        id: cmaRestGet
        uses: fjogeleit/http-request-action@v1
        with:
          url: http://mule-app-config.us-e2.cloudhub.io/api/errorConfig/validate
          method: 'POST'
          data: |
            {
              "servicenowGroupId": "679434f053231300e321ddeeff7b12d8"
            }
      - name: Validation response
        run: |
          echo ${{ steps.cmaRestGet.outputs.valid }}
          echo ${{ steps.cmaRestGet.outputs.error }}   
  get_dad_joke:
    name: A dad joke is your reward!
    runs-on: ubuntu-latest
    needs: sample_rest_user
    steps:
      - name: Get Dad Joke via pwsh
        run: |
          $dadJoke = (Invoke-RestMethod -Method 'Get' -Uri 'https://www.reddit.com/r/dadjokes/random.json?limit=1').data.children[0].data
          Write-Host $dadJoke.title
          Write-Host $dadJoke.selftext
        shell: pwsh