name: Noodling with GitHub Actions
on:
  push:
    paths:
      - 'README.md'
  workflow_call:
 
jobs:
  sample_rest_user:
    name: Validate Mule Configuration
    runs-on: ubuntu-latest
    steps:
      - name: Call Mule Config Validation API
        id: muleValidation
        uses: fjogeleit/http-request-action@v1
        with:
          url: http://mule-app-config.us-e2.cloudhub.io/api/errorConfig/validate
          method: 'POST'
          data: |
            {
              "servicenowGroupId": "${{ secrets.SERVICENOW_GROUP }}"
            }
      - name: Validation response
        run: |
          echo ${{ fromJson(steps.muleValidation.outputs.response.valid) }}
          echo ${{ fromJson(steps.muleValidation.outputs.response.error) }} 
  get_dad_joke:
    name: A dad joke is your reward!
    runs-on: ubuntu-latest
    needs: sample_rest_user
    steps:
      - name: Get Dad Joke via pwsh
        run: |
          $dadJoke = (Invoke-RestMethod -Method 'Get' -Uri 'https://www.reddit.com/r/dadjokes/random.json?limit=1').data.children[0].data
          Write-Host $dadJoke.title
          Write-Host $dadJoke.selftext
        shell: pwsh